#!/bin/sh

if [ ! -x /usr/sbin/wd_keepalive ]
then
    exit 0
fi

if [ "$1" = "stop" -o "$1" = "restart" ]
then                                                                            
    echo "Stopping the watchdog daemon: "
    killall wd_keepalive
fi

if [ "$1" = "start" -o "$1" = "restart" ]
then
    echo "Starting the watchdog daemon: "
    /usr/sbin/wd_keepalive
fi
